### ISSUE TITLE
Can't properly add and can't remove the Mustard UI in 3.5.1

### ISSUE THREAD

**Issue by TheCalibrator** [Mustard2/MustardUI#103]
This is how the UI looks when added in 3.5.1
![image](https://github.com/Mustard2/MustardUI/assets/98053058/a76c1672-2830-4980-a602-5b1009c7d39a)

I can't find a way to finish the setup and there is no option to remove it.

Edit: the last drop down menu is empty.

**Comment by Mustard2** [comment]
Hi! :)

Might be that they changed something in 3.5.1. It seems an icon issue. Which version of MustardUI are you trying to add?

**Comment by TheCalibrator** [comment]
Hey, I'm so glad to see you right now. I was trying to add that one version you gave me a while back but I'm not at home so I can't see the exact number. 0.26 if I remember correctly.

**Comment by Mustard2** [comment]
Reopened :D

Very weird, can you open the console and check what's the error you see? Because I tried on mine and it works.

**Comment by TheCalibrator** [comment]
Hmm I'll have to get back to you when I'm home about this. In the meanwhile can you tell me which version worked for you?

**Comment by TheCalibrator** [comment]
Ok so I think if it worked for you it would be best to consider this issue closed. I'll try this version because i think the other one is older and I made a bad choice not checking the versions here. I will let you know if there are any issues. 

Also should I just run the latest script over the one I have now? I'm asking cause I don't have a save before I added the old version unfortunately, so it's stuck there.

**Comment by Mustard2** [comment]
Remove the old one and put the new one. This should be the last time you do so, from next version 0.26 there is an update function available :)

**Comment by TheCalibrator** [comment]
All right. That update function sounda real nice. I gotta ask 1 more question then. Do I just need to remove the script to remove this old UI version?

**Comment by Mustard2** [comment]
You can copy paste the new code on the old one if you want

**Comment by TheCalibrator** [comment]
Got it. I'll let you know how it goes. Thanks.

Also a little side track, I have a present for your models. I made fake eye caustics that work for cycles. Dm me on Discord if you want a preview or the nodes.

**Comment by Mustard2** [comment]
Thanks! :)

I'm having a bit of troubles logging in in Twitter and Discord, as they stole my phone with the authenticators. :(
Hope to solve this soon..

**Comment by TheCalibrator** [comment]
Is there anything you use that I can DM you through?

**Comment by Mustard2** [comment]
Patreon atm, which is not great I know. :(

**Comment by TheCalibrator** [comment]
Yes, it worked. Thanks a lot!
