### ISSUE TITLE
Simplify affected option not properly returning to default selection

### ISSUE THREAD

**Issue by mokujinh** [Mustard2/MustardUI#111]
I use the solidify option in the menu quite often to simulate outlines for anime models.
The simplify option does successfully turns the solidify modifiers off in the viewport to facilitate the workflow speed. The problem is, after turning the simplify option off again, these solidify modifiers (being for body, hair and outfits) remain turned off (even for render mode) no matter if I had the previously set as On in the menu before using the simplify option.
This can result in entire rendering sessions being wasted as users won't notice this option remains turned off immediately (happened to me lol). By now I just check them back on after turning the simplify option off, but that kinda defeats the purpose of that tool being there to begin with I imagine.
Figure I should have reported this a while ago but I just got back on working with anime models and remembered this issue, it's been there ever since the solidify options were added for the body and hair if that's any help. Cheers!

**Comment by Mustard2** [comment]
Hi! Is this problem only happening for soldify?

**Comment by mokujinh** [comment]
Yes, only for the solidify options. Everything else returns to normal after turning Simplify Off

**Comment by Mustard2** [comment]
[mustard_ui.zip](https://github.com/Mustard2/MustardUI/files/12687775/mustard_ui.zip)

Can you please try with this?
I made a mistake indeed. :)

**Comment by mokujinh** [comment]
Works like a charm now, thanks :)

**Comment by Mustard2** [comment]
Great! I'll push the update then :)
