### ISSUE TITLE
ZIP file failed to register plugin

### ISSUE THREAD

**Issue by oulaobiao** [Mustard2/MustardUI#112]
I can't register the plugin after installing the zip file, but installing the py file directly can register the plugin, I don't know if there is a problem, the blender is version 3.6

**Comment by Mustard2** [comment]
Hi! Blender addons that have just one file (one .py) must be installed without the zip.

Consider that this is supposed to be a script, it's better to use it as that. That is, run it through Blender text editor and include it in your model - there's a register button to do the latter.

Let me know if this solves your issue. :)
