### ISSUE TITLE
MHX 1.7.0.0073 crash & block blender file on blender 3.6.4

### ISSUE THREAD

**Issue by Dodododo998** [Mustard2/MustardUI#116]
The MHX addon blocks the blender file and prevents it from reopening. I encountered the problem the first time when I exported Aerith's model to a new Blender file. After exporting I tried to use the 'snap IK/FK all' function and the blender file crashed and stopped responding permanently. Reopening the file was impossible (unresponsive).
I later tried uninstalling the addon in a new file blender, and was able to reopen the file.
I tried using the same command on the original file (the Aerith model one) and it worked without problems.
On the import file I tried to reinstall the MHX addon and it worked fine, at least until the file was closed. After closing and reopening the file I had the same problems again.
It is also not possible to render. If I launch the render with the F12 command as render I only see the squared screen (as if I had rendered a scene without objects and with transparency active).
I'm continuing to test to add more details.
I have NEVER had problems with this addon, only with Aerith's model did I have these problems.

**Comment by Mustard2** [comment]
Hi! It seems this is a problem of MHX and not of MustardUI?

Anyway we can check: can you please open Blender through the console? It should tell you the error when Blender crashes.

Paste here the error. :)

**Comment by Mustard2** [comment]
Closing this as it doesn't seem a MustardUi issue.
Re-open this or another issue if you still have problems. :)
