### ISSUE TITLE
Is the autmatic update discontinued for the script version on older Blender versions? (pre 4.0)

### ISSUE THREAD

**Issue by mokujinh** [Mustard2/MustardUI#129]
**Describe the bug**
I wonder with the tool moving to an Add-on format, if the UI script support was discontinued? 
I get this error when trying to update older models with older script versions. 

<img width="346" alt="25346" src="https://github.com/Mustard2/MustardUI/assets/103069542/ca0360a5-c123-4c98-8e00-a529639ac1a9">

Tried on MustardUI version 0.026.0.022 Internal updater
Also tried manually updating it to 0.027.0.032 which worked but the updater still gives that error anyway instead of behaving as it used to.

**Comment by Mustard2** [comment]
Hi @mokujinh 

unfortunately the update as it was implemented in the script is not compatible with the addon.

I will add a new addon updater later, but at the moment the change to addon also removed the possibility for the updater to be used on older versions. :(

Is this a priority in your opinion?

**Comment by Mustard2** [comment]
I added a version check tool in #128 . Updating it from there is another level of complexity

**Comment by Mustard2** [comment]
As a workaround if you need files to work with Blender 3.6, just substitute this link (search in the script file)

`https://raw.githubusercontent.com/Mustard2/MustardUI/master/mustard_ui.py`

with

`https://github.com/Mustard2/MustardUI/blob/72f08a784acf9e56f4d14ee760eca310999182ae/mustard_ui.py`

**Comment by mokujinh** [comment]
Interesting, I would suggest perhaps leaving a last update for the script version for people that will still not move to the Add-on version, just a warning when pressing "check for UI updates" about the transition to add-on. So that people that don't frequent or work with models that often find out about this transition more easily. If it's not very difficult.

**Comment by Mustard2** [comment]
It's not difficult, but it would still require people to manually update the script, and thus they would already know that something changed, making the added message redundant.. :(
