### ISSUE TITLE
Custom properties for hair

### ISSUE THREAD

**Issue by datquil** [Mustard2/MustardUI#137]
I'm trying to add a custom property (shapekey in this case) for one of the hair objects. However it throws an error after adding it. It only shows up in configuration mode. The property itself works normally but I don't know if it's something to be concerned about.

![image](https://github.com/Mustard2/MustardUI/assets/110947332/65e8a04b-4140-4b50-9923-638a50591f57)

![image](https://github.com/Mustard2/MustardUI/assets/110947332/660d9b40-a48b-4d20-965a-f24c77e59070)

Using addon version 0.30.2.15
Blender 4.0.0

**Comment by Mustard2** [comment]
Thanks! There was an error in one line causing this to happen if MustardUI Naming Convention was enabled.
Fixed in #139

**Comment by Mustard2** [comment]
[MustardUI-Version-0.30.3.zip](https://github.com/Mustard2/MustardUI/files/13623846/MustardUI-Version-0.30.3.zip)

If you want to use the new version, this is the file in the meanwhile.

**Comment by datquil** [comment]
Thanks! It works now.
