### ISSUE TITLE
"ID user decrement error"

### ISSUE THREAD

**Issue by mokujinh** [Mustard2/MustardUI#141]
I seem to have come through some errors with the Add-on version after checking the console after blender crashed on me a couple of times.

Here are some screen of the errors and what it causes.
<img width="1295" alt="2351432513425" src="https://github.com/Mustard2/MustardUI/assets/103069542/afed3b23-2ca6-4d66-8384-8cdf698dfcc2">

<img width="292" alt="4124124" src="https://github.com/Mustard2/MustardUI/assets/103069542/d0d8065f-ef4f-4d1d-bb38-2e306abc9d3e">

Apparently it causes many fake users and also it crashes blender when I try to open or make a new project as well.

I tried uninstalling the latest UI Version 3 and blender won't crash anymore and the errors won't show up on the console anymore.

This happen to a model I updated from 3.6 to 4.0, (I appended the model to a clean project first). 

I tested the older models version in blender 3.6 with the script version of MustardUI and they work fine and the errors won't show on the console either.

**Comment by Mustard2** [comment]
Wow this seems like a major issue.

I did see those errors in the console, but I thought it was just a small warning from Blender. Apparently, it isn't.

Let me check. :)

**Comment by Mustard2** [comment]
It seems like it's a Blender bug. I reported it:
https://projects.blender.org/blender/blender/issues/116061

**Comment by Mustard2** [comment]
It seems it will be fixed in Blender 4.1 :)
