### ISSUE TITLE
Surface Deform Option for Outfits

### ISSUE THREAD

**Issue by Slyxxx24** [Mustard2/MustardUI#145]
Hi, I'd like a **Surface Deform** option to be available in the **Outfit Global Properties** as it works better than **Shrinkwrap**. There is some trouble-shooting to get it functional on some models but the results speak for themselves. If possible, a '**BIND/UNBIND**' option could also help speed things up as it is required for the modifier. All you need to do is to make a Proxy of your model and set it as the Target.

**"Target Contains Concave Polygons" (Common error)**
-select Proxy mesh > Edit Mode > select all vertices
-Mesh > Clean Up > Split Concave Faces
**To View Problem Causing Vertices**
-Edit Mode > Select All By Trait > Non Manifold

**Comment by Mustard2** [comment]
Thank you for the feedback, I'll add it in the next version :)
