### ISSUE TITLE
Error when removing custom properties

### ISSUE THREAD

**Issue by ArcadiaBaes** [Mustard2/MustardUI#146]
Hello,
I would like to remove a custome propertie i made, but its impossible. Everytime i click on the cross i get this message

![image](https://github.com/Mustard2/MustardUI/assets/155725109/43473429-96f6-4287-bd0d-89e7d4f63025)

**Comment by Mustard2** [comment]
Hi!

This has been fixed recently in the new upcoming version: https://github.com/Mustard2/MustardUI/pull/144
If you want there is also a download for the current test version to try, and you can check if you still see the error.
