### ISSUE TITLE
UI keeps nullifying previous custom properties when new ones added

### ISSUE THREAD

**Issue by J4ke6599** [Mustard2/MustardUI#153]
I've had to redo my scene because there were some unfixable issues not related to this UI, but as I'm trying to readd some properties, a new property added to the UI keeps making previous properties in the UI not even work even if they're turned on.

For example, I've got a few properties affecting multires modifier where it's turned on with a boolean custom property. Well, when I add a shape key affecting the main body, it then makes the multires properties not work. Then when I readd those back, the shape key property doesn't work. Then wise versa.

Am I losing my mind or what is this?

**Comment by Mustard2** [comment]
Hi! Do you have the Blender file with the error I can check?

You can remove the textures.

**Comment by J4ke6599** [comment]
Hey I realized that the problem can be fixed with the Rebuild properties function, though I'm not sure why it kept making the previously added property not working.

Though, I have another issue. I've got two UI integrations in the new scene, because somehow the older one got imported when I was appending stuff from the old scene to the new scene. And I'm unable to remove the duplicate old UI.

**Comment by Mustard2** [comment]
@J4ke6599 I see. So everything is ok now? :)

Please let me know if you find any other bug opening a new issue, I'll close this in the meanwhile.
