### ISSUE TITLE
Forced to open Edge for updates

### ISSUE THREAD

**Issue by mokujinh** [Mustard2/MustardUI#156]
this is a minor detail that I won't even consider an issue, but it's interesting non the less: 
When adding my custom links to my pages for the creator links section, the links will open on my default navigator of choice in windows, same for the mustardUI references links. But for some reason the MustardUI update warning link forces you to open this github page on Microsoft Edge, I and many people rather not use Edge at all and I don't know if it's even in your possibilities to check that, but it is a curious difference between other links shared using the UI. Is it possible to make that link also open on the user's default navigator of choice in windows like all other links?

**Comment by J4ke6599** [comment]
Yep noticed the same, even though Firefox is my default browser.

**Comment by Mustard2** [comment]
Hi! It seems like a problem of Python package webbrowser.

I'll check if there's something that can be done about it, but I'm not the author of that. :(

**Comment by Mustard2** [comment]
I checked and unfortunately it seems a bug of the webbrowser package. In principle the function I'm calling should open the default browser (like it does for me), but sometime it might fails.

Have you tried to make Edge as default, and then set as default the one you want?

**Comment by Mustard2** [comment]
[MustardUI-default-browser-fix.zip](https://github.com/Mustard2/MustardUI/files/14722725/MustardUI-default-browser-fix.zip)

Also I tried a quick fix as suggested by others. @mokujinh @J4ke6599 can you please check if it stills open Edge?

**Comment by Mustard2** [comment]
Ok pushed a new version with this fix, please open a new issue if this is still not working. :)
