### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by ilego1** [Mustard2/MustardUI#158]
I was wondering if this could somehow be used to help me convert OBJ or FBX to NIF? Because when I read it the documention what appealed to me was how you color coded it to show what not to do otherwise you would mess up the model. To clarify I am trying to make a fallout 4 outfit but my biggest fear is that I learn all this stuff and then it becomes pointless not because I can’t use it but because I only want to upload 3 or 4 models. So I will be out of practice.

**Comment by Mustard2** [comment]
Hi!

The addon works with any rig, even custom ones (not necessarily Rigify, APR, MHX or others). The import mesh format is not something the UI cares about, what's important is that you have an Armature.

Or am I missing something?

**Comment by ilego1** [comment]
To be honest it’s been a while a couple of weeks give me a second

**Comment by ilego1** [comment]
> Hi!
> 
> The addon works with any rig, even custom ones (not necessarily Rigify, APR, MHX or others). The import mesh format is not something the UI cares about, what's important is that you have an Armature.
> 
> Or am I missing something?

To be clear I was referring to this part and I probably misunderstood it in my excitement. I a. Trying to make a fallout 4 outfit mod and am new so I thought this would help by explaining to me what buttons do what when I try get uv maps set
![IMG_1901](https://github.com/Mustard2/MustardUI/assets/58491966/e519f464-fcfe-4832-95ec-e6ee12000688)

**Comment by ilego1** [comment]
My apologies I just Am at a loss. at first I see everyone using Blender so I do as well (am very new) and with help I, somehow, got my Blender File exported as a obj with the MTL actually recording the maps and showing up in nifskope. I then have problems figuring out how to use gimp to create the 3 dds and not just because I can’t save in dds format. I find out later it requires plugin that nobody mentioned me needing So I try once again and it doesn’t show up in nifskope and while I have a very basic understanding the dds files I don’t know exactly which picture it shows so I can’t figure out how to chose the correct starting point. I have the mesh and textures i know I can do it myself if someone can just get the export thing done at least I guess?

**Comment by Mustard2** [comment]
If you need to convert images, you can use for instance: https://imagemagick.org/index.php
It's better to use PNGs in Blender.

**Comment by Mustard2** [comment]
Closing for now, if you have any other issue please open a new Issue :)
