### ISSUE TITLE
Update custom property type automatically in the UI?

### ISSUE THREAD

**Issue by J4ke6599** [Mustard2/MustardUI#160]
Right now, if you set a custom property as a boolean or float or something, but want to change it to something else, it doesn't automatically update in the UI, even if you rebuild properties. You have to delete the property and re-add it back to update it in the UI.

Is it possible to make it so that the property type changes when you press an update or refresh button?

**Comment by Mustard2** [comment]
Hi! What do you mean by "change with somethine else"? Are you truing within MustardUI or changing the settings somewhere else?

**Comment by Mustard2** [comment]
Closing this as there was no new message. If the issue persists, please open a new one here. :)
