### ISSUE TITLE
Updates not opening

### ISSUE THREAD

**Issue by mokujinh** [Mustard2/MustardUI#163]
As requested at #156 for feedback about the "edge only" update link in the UI. The provided version won't open a link at all now after the "press ok" message shows.

**Comment by Mustard2** [comment]
Very weird, Ijust tried and it works for me.

@mokujinh Can you try to install this and check the version?
I changed the version to be less than the remote one just for this check.

[MustardUI-default-browser-fix-3.zip](https://github.com/Mustard2/MustardUI/files/14732907/MustardUI-default-browser-fix-3.zip)

**Comment by mokujinh** [comment]
Can confirm it works fine now.

**Comment by Mustard2** [comment]
Ok, great, I'll merge and push a new update :)
