### ISSUE TITLE
Suggestion: Make update check opt-in option!

### ISSUE THREAD

**Issue by cl3m3c7** [Mustard2/MustardUI#165]
Hi,
I want to suggest to make update check a settings in the prefs (enabled by default?) because if you have slow a connection or no internet but connected to the network 😕, blender freezes until the plugin gets a result back!

**Comment by Mustard2** [comment]
Upsi, didn't think about it.
I'll surely make it optional in the next update.

**Comment by cl3m3c7** [comment]
thanks, I know it's very specific and rare case since people nowadays have good internet, but yeah it's nice to have!

**Comment by Mustard2** [comment]
I perfectly agree, I'll ake the updates check optional and disabled by default :)

**Comment by cl3m3c7** [comment]
> I perfectly agree, I'll (m)ake the updates check optional and disabled by default :)

in my humble opinion, I think it should be enabled by default because 99% of the time this shouldn't create any problem, but in those rare cases where the bottleneck occurs, one can choose to disable it!

**Comment by Mustard2** [comment]
Yes, I think I'll make it enabled by default in the end. :)
