### ISSUE TITLE
All sections deleted for some reason from scene(s)

### ISSUE THREAD

**Issue by J4ke6599** [Mustard2/MustardUI#170]
I had some issues with Mustard, which required me to reinstall it. But after  a while, I noticed that for some reason ALL the sections were deleted off of the UI and worse is that  I had already saved the scene before I noticed this.

Is there any way to fix this?

I didn't un and reinstall Mustard while I had the scene open.

**Comment by J4ke6599** [comment]
Okay so what the hell, I reinstalled Mustard again and now it's back to normal.

**Comment by Mustard2** [comment]
So is it ok now?

**Comment by Mustard2** [comment]
Closing this, if there are other issues please let me know opening a new Issue here. :)
