### ISSUE TITLE
Error won't allow to add custom shader properties

### ISSUE THREAD

**Issue by mokujinh** [Mustard2/MustardUI#171]
Error: 
```
Python: Traceback (most recent call last):
  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\MustardUI\menu\menu_configure.py", line 125, in draw
    sec = rig_settings.body_custom_properties_sections[scene.mustardui_section_uilist_index]
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0
```

The conditions for this error may be (not sure) because I added the old MustardUI Float/Bool names to the initial values for some skin shader properties, example: 
Value node name: MustardUI Float - Subsurface
Value node label: Subsurface

While working in configuration mode every other option (including end configuration mode) will disappear after that error message, it'll come back after I manually delete the shader property, BUT it won't let me manually add the node values properties again without the error showing up again now, even after changing back the value nodes names without the mustardui part on it, not allowing me to continue configuring the model.

**Comment by Mustard2** [comment]
Can you send me the Blender file?

**Comment by mokujinh** [comment]
> Can you send me the Blender file?

Here: https://drive.google.com/file/d/1OHlXGUYiNJF9fZiU18Mc_0noqCvShNBB
Blender version: 4.1.1
UI version: 0.31.1.9

**Comment by mokujinh** [comment]
By the way, deleting the shader property is the only way to advance and finish the configuration mode, otherwise it gets "locked"

**Comment by mokujinh** [comment]
For the record, these are the steps that lead to this error:

Created multiple value based properties in the shader editor (subsurface, wetness, nails color, makeup, etc).

They all included the old name format: "MustardUI Float - Subsurface"

Making the UI search for the properties on it's own in configuration mode lead to the error.

What I did to try to solve it but didn't work: 

I deleted the properties from the UI menu, that made the remaining options including the ability to "end" configuration mode to come back.

>Manually added the properties again, didn't work, lead to the same error.
>Renamed the properties deleting the MustardUI Float name out of them, didn't work, lead to the same error.
>Duplicated, deleted old mesh, purged, and restarted the UI configuration from scratch with new clean model, didn't work, lead to the same error.
>Deleted and assigned new materials individually before adding properties again, didn't work lead to the same error.
>New completely different model
>Manually tried to add the properties values in configuration mode, same error.
So I think this is a global thing present for this version of the UI, no idea how to make this work.

**Comment by Mustard2** [comment]
Ok, I'll take a look asap! Sorry I'm a bit busy lately :(

**Comment by Mustard2** [comment]
Ok I found the issue, it was a missing check on the length of the section container.
I'm pushing a new version.

Thanks for reporting this!
