### ISSUE TITLE
Dont Show the Preferences check box for developer tools in the addon tab ! Help

### ISSUE THREAD

**Issue by LucasSculpt** [Mustard2/MustardUI#181]
![Screenshot_1](https://github.com/user-attachments/assets/ece6c3c7-6ef1-4747-9df4-08c0755221c4)
 
Sorry i just know the amazing addon and i would like to use it in my characters but i cant activate the dev tool, the preferences canvas don't have  appear in my blender ! Please I've make something wrong?

![Screenshot_2](https://github.com/user-attachments/assets/9f25ddfd-0f6d-4746-8634-20514cc4abe7)

**Comment by LucasSculpt** [comment]
I forget mention if i was making something wrong ?

**Comment by Mustard2** [comment]
Yes just for reference for other people, unfortunately they made the things quite confusing. The actual addon settings are now in the other Extensions panel :(

**Comment by LucasSculpt** [comment]
Thanks about it !
