### ISSUE TITLE
UI and model errors

### ISSUE THREAD

**Issue by MarciMcFly** [Mustard2/MustardUI#184]
Hi! I am having several issues, I haven't found any previous mentions of either of them.

I just downloaded my first Mustard model, Tifa. I am using Blender 4.2.3 and have DAZ Importer 4.2.1 and MHX Runtime System 4.2.1 installed, as described in the requirements.

First of all, by opening tifa5_v1_9_2.blend, I am immediately greeted by the following three Python error messages:

1.
```
Python: Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\MustardUI-master\menu\menu_tools_creators.py", line 17, in poll
    addon_prefs = context.preferences.addons["MustardUI"].preferences
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'bpy_prop_collection[key]: key "MustardUI" not found'
```

2.
```
Python: Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\MustardUI-master\menu\menu_configure.py", line 19, in poll
    addon_prefs = context.preferences.addons["MustardUI"].preferences
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'bpy_prop_collection[key]: key "MustardUI" not found'
```

3.
```
Python: Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\MustardUI-master\menu\menu_configure.py", line 34, in draw
    addon_prefs = context.preferences.addons["MustardUI"].preferences
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'bpy_prop_collection[key]: key "MustardUI" not found'
```

Nevertheless, I have the MustardUI in the side panel, morphs and outfits, rigs are working, but:
- When I can click on the triangle next to the UI Configuration, Settings and Hair dropdown menus, they are all empty.
- Naturally, there is no Physics menu either for example.
- I get a similar Python error if I try to enable Auto Blink, this time the error is in auto_eyelid.py, row 37.

I tried to install MustardUI-0.32-beta1.zip, I again get an error: No module named 'MustardUI-0', so that didn't help.

Also, Tifa is unmovable with G, something is locking her body in place. If I drag her by dragging the mouse on the X or other coordinates in the right side menu (N key) - Tool menu, she moves but her eyes fly in the opposite direction and her limbs stretch out more the further I move her, so she becomes an eldrich horror. How are we supposed to move her around to fit her into scenes? I also couldn't find an answer to this in the docs. _<- Please disregard this, I've found I can unlock transformations in the side panel and should only move her body parts in Pose mode._

I don't know if these issues are connected or not, but I haven't found anyone else having had any of them in the past, so in lieu of a better idea, I am writing them down here.

Let me know if I should provide more info!

Many thanks for your help in advance as these issues are quite frustrating, I cannot use the model at all!

**Comment by Mustard2** [comment]
Sorry for the confusion, you should download the file from here, otherwise it won't work:

https://github.com/Mustard2/MustardUI/releases/tag/0.32-beta1

This is due to several changes they made from 4.1 to 4.2, and also some limitations regarding the naming of the folders

**Comment by MarciMcFly** [comment]
Many thanks for your reply! Downloading the UI from this link worked. I installed it successfully, and there are no errors.

Cheers!
