### ISSUE TITLE
ROOKIE ASKIN: Sculpt Model Body went wrong

### ISSUE THREAD

**Issue by DickinHI** [Mustard2/MustardUI#188]
why sculpt that body went a huge out of shape , no matter I use what kinds of Vertex Group or cut off Strength.  ROOKIE ASKIN FOR HELP  : )

**Comment by Mustard2** [comment]
Hi!
This does not seem a UI bug, closing the issue. If you want to discuss general things, please open a discussion in the Discussion panel.

**Comment by DickinHI** [comment]
Sorry for that ! Thanks for the reply, I will go check in  The Discussion!
