### ISSUE TITLE
Implemented - MHX bone collection import

### ISSUE THREAD

**Issue by J4ke6599** [Mustard2/MustardUI#190]
Is it possible to that you could automatically detect and add the bone collections added with the MHX rig to the UI?

I keep a raw, unrigged version of my models every time I do some changes so adding all the 15 or 20 collections isn't really fun to do each time I make a version of the model rigged to the Diffeomorphic MHX system.

**Comment by Mustard2** [comment]
Yes it's a feature of the new version. :)

Please let me know if it doesn't work opening a new Issue. Closing this as the feature has been implemented in a recent version.

**Comment by Mustard2** [comment]
As a comment: some other addon rigs will be added (ARP and Rigify) soon™
