### ISSUE TITLE
Performance Loss After Adding Outfits

### ISSUE THREAD

**Issue by m-155** [Mustard2/MustardUI#37]
Prior to adding outfit collections to MustardUI my viewport FPS is 60-62. After adding 12 outfits to MustardUI, viewport FPS drops to 50-52. If I delete the outfits from MustardUI, I do not gain the ~10 FPS back. All clothing is disabled in viewport and no custom properties were added. 

It's a 'permanent' loss I've not been able to figure out how to recover from. Even if I remove MustardUI from my blend ("UI Removal"), unregister script, save, reload, etc -- I never gain that 10 FPS back. 

I have tested this multiple times with backups and the same thing happens every time.

Any suggestions?

**Comment by Mustard2** [comment]
Hi!

Thank you for reporting this.

Some questions about the issue:
- Did you also add custom properties, or just the outfits?
- Have you disabled all modifiers of the outfits? It might be that the shrinkwrap/smooth correction modifiers are enabled by the UI, and can be disabled with the buttons after the outfits list.
- Do you have a .blend file I can check? If you want you can send it to me on Twitter/Discord.

**Comment by m-155** [comment]
1 - Just outfits.
2 - The only modifiers any of the clothing objects have are armature and subsurf. In Blender's 'render settings' tab I have simplify enabled and set to 0 for viewport. 
3 - Blend sent via Discord

**Comment by Mustard2** [comment]
Thank you for the answers and the blend file. I will surely look into it asap. :)

**Comment by Mustard2** [comment]
Ok, I analysed your file. It seems that you have some dependency cycles with the drivers that get additional performance decrease when you also add outfits.

You can see it from the console, just open it and you'll see a lot of messages with "Driver serialization" issues. I am not sure where they come from (maybe something went wrong in the Diffeomorphic import?). Removing all drivers from the file, even if you add the outfits you don't get any decrease in performance. Contact me on Discord if you need more help about this.

I close this as "Not an issue", but feel free to re-open it/open a new issue if with the suggested fix specific for your file you're still getting performance decrease. :)
