### ISSUE TITLE
Lips shrinkwrap tool doesn't work on latest diffeomorphic imported models

### ISSUE THREAD

**Issue by BobBoxArt** [Mustard2/MustardUI#56]
Lips shrinkwrap tool doesn't work on development version diffeomorphic imported models.

**Comment by Mustard2** [comment]
I will check this, and see if there is an issue with bone naming in the new version.

**Comment by Mustard2** [comment]
Ok, I found the issue: the naming of the bones was changed. Will be fixed in the new version. Thank you. :)
