### ISSUE TITLE
[Orphan Data Issues] Armature and Body

### ISSUE THREAD

**Issue by mokujinh** [Mustard2/MustardUI#69]
Manually deleting models and rigs from the viewport and or outliner doesn't seem to be enough to get rid of unused data. If the script is applied to a rig, the deleted rig will remain in the blender data even if you use the blender purging methods to delete unused data.
You'll have to manually check the blender file linked libraries and look for the deleted rig to manually delete it, this problem remains even if you use the "remove UI" tool integrated with the menu before deleting the rigs.

This error makes it so that all the data linked to the rig will also remain even after purging. Which can cause conflicts and affect rendering and loading times. So far the walk around seems to be to manually delete thing sin the blender data library and manually removing the script and reloading blender before proceeding.

**Comment by Mustard2** [comment]
Related to #45 , a better handling of data removal for armature, body and outfits is needed.

Thanks for reporting this. :)

**Comment by Mustard2** [comment]
Tool added in Version 0.25.
