### ISSUE TITLE
How to add Custom Properties

### ISSUE THREAD

**Issue by celticsamurai** [Mustard2/MustardUI#75]
Hey I'm kinda new here. I'm trying to figure how I would add custom properties to MustardUI. If I missed it in the wiki, I'm really sorry.

**Comment by Mustard2** [comment]
No problem! You can add them in Configuration mode only, and just right clicking on any Blender property.
For instance, if you want to add a RGB color input, just go in Configuration mode and right click on it. At the bottom there are some buttons to add it.
Let me know if it works. :)

**Comment by celticsamurai** [comment]
Okay thank you very much. Now how would I make these properties into a checkbox?

**Comment by Mustard2** [comment]
Once you add the properties, they'll show up in the Configuration menu (in Body, Outfit or Hair, depending where you add the properties). Just click on the settings button on the right of the list of properties, and you can force another data type (from float to bool or int).

**Comment by celticsamurai** [comment]
Where would I go to force that?
![image](https://user-images.githubusercontent.com/101759519/189240032-7410662a-5023-4fbb-82c7-c72309dab5d4.png)

**Comment by Mustard2** [comment]
Ok this is because you added something that is already int. I think only float properties are supporting data type change.
Is that a property from a material? If yes, substitute whatever you're using with a Value node, that will be float.

**Comment by Mustard2** [comment]
If you can tell me which property you added, maybe I can also push a new update for that data type. :)

**Comment by Mustard2** [comment]
Closing this, but if you still have problems/need to discuss about this, please re-open this or create a new issue. :)
