### ISSUE TITLE
Smart Scan Error/Failure when Body mesh contains an empty material slot

### ISSUE THREAD

**Issue by Realium3D** [Mustard2/MustardUI#83]
Discovered an issue with the Smart Scan feature and the Properties Smart Check when an empty material slot is present on the Body mesh. The following error occurs when running Smart Check:

`Python: Traceback (most recent call last):
  File "\mustard_ui.py", line 4862, in execute
  File "C:\Users\ADMIN\Documents\Blender\stable\blender-3.3.0\3.3\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "\mustard_ui.py", line 3561, in execute
AttributeError: 'NoneType' object has no attribute 'node_tree'
Location: C:\Users\ADMIN\Documents\Blender\stable\blender-3.3.0\3.3\scripts\modules\bpy\ops.py:113
`

And the following with Properties Smart Check:

`Python: Traceback (most recent call last):
  File "\mustard_ui.py", line 3561, in execute
AttributeError: 'NoneType' object has no attribute 'node_tree'
`

The fix/workaround is to remove the empty material slot from the Body mesh.

**Comment by Mustard2** [comment]
Hi! Thank you for the report.

It surely seems a bug. If confirmed, I'll fix it with a better handling of that exception. :)

**Comment by Mustard2** [comment]
Fixed in 0.25.1.007
