### ISSUE TITLE
Global Solidify for Anime/Toon models

### ISSUE THREAD

**Issue by mokujinh** [Mustard2/MustardUI#91]
Adding a global solidify modifier control to the menu, similar to the smooth modifier or subdivision modifier controls, could be really useful for those who use and make anime/toon shaded models, being a global property for the body, outfits and hairs or even extras, (there's already a solidify option for outfits) could be a great addition, as the solidify modifier mixed with a black material is usually made to "fake" the black outlines you'll see in any drawn cartoon characters, it works better than using the compositor or freestyle features included in blender. However this trick would obviously cost a lot more resources in the viewport. Having an option to globally turn the modifier on and off in the viewport could save people A LOT of time while animating and previewing stuff in the viewport.

**Comment by Mustard2** [comment]
Hi! I think it might be a good idea. I'll add it in the next version :)

**Comment by Mustard2** [comment]
Added in 0.26.0
