### ISSUE TITLE
Multiple outfits options per armature layer

### ISSUE THREAD

**Issue by mokujinh** [Mustard2/MustardUI#94]
If there's a chance to add more outfit options for the bone layers when changing the outfits, that would save a lot of layer space when having one bone for multiple outfit parts, for example, a tie set of bones working for two different set of ties in two different outfits using just one bone layer instead of duplicating the bones for another bone layer.

**Comment by Mustard2** [comment]
Thinking on how to implement this: either we switch to just hide/show bones instead, or atm I'm out of ideas.

**Comment by Mustard2** [comment]
Since in the new Blender 4.0 you can create unlimited armature layers, I guess this is solved in #120 .
